<?php

namespace Illuminate\Support {
    /**
     * Carbon
     * @method bool isAlgerianIndependenceDay
     * @method bool isAlgerianLaborDay
     * @method bool isAlgerianRevolutionDay
     * @method bool isAmazighNewYear
     * @method bool isBrazilianDayOfTheDead
     * @method bool isBrazilianIndependenceDay
     * @method bool isBrazilianLaborDay
     * @method bool isBrazilianRepublicProclamationDay
     * @method bool isTheDayOfOurLadyAparecida
     * @method bool isTiradentesDay
     * @method bool isBoxingDay
     * @method bool isCanadaDay
     * @method bool isCanadianThanksgiving
     * @method bool isCivicHoliday
     * @method bool isFamilyDay
     * @method bool isLabourDay
     * @method bool isRemembranceDay
     * @method bool isVictoriaDay
     * @method bool isDutchLiberationDay
     * @method bool isDutchNationalDay
     * @method bool isDutchRemembranceDay
     * @method bool isSaintNicholasEve
     * @method bool isEgyptian2011RevolutionDay
     * @method bool isEgyptian23JulyRevolutionDay
     * @method bool isEgyptian30JuneRevolutionDay
     * @method bool isEgyptian6OctoberVictoryDay
     * @method bool isEgyptianChristmasDay
     * @method bool isEgyptianLabourDay
     * @method bool isEgyptianNationalPoliceDay
     * @method bool isEgyptianSinaLiberationDay
     * @method bool isAscensionDay
     * @method bool isAssumptionDay
     * @method bool isEasterMonday
     * @method bool isFirstWarArmisticeDay
     * @method bool isFrenchNationalDay
     * @method bool isPentecostDay
     * @method bool isSecondWarArmisticeDay
     * @method bool isAscensionOfJesus
     * @method bool isCorpusChristi
     * @method bool isGermanLabourDay
     * @method bool isGermanUnityDay
     * @method bool isHeiligAbend
     * @method bool isHeiligerAbend
     * @method bool isPentecost
     * @method bool isPentecostMonday
     * @method bool isPentecostSunday
     * @method bool isWhitMonday
     * @method bool isWhitSunday
     * @method bool isWhitsun
     * @method bool isGandhiJayanti
     * @method bool isIndianIndependenceDay
     * @method bool isIndianRepublicDay
     * @method bool isIndonesiaCustomerDay
     * @method bool isIndonesianEducationDay
     * @method bool isIndonesianHeroesDay
     * @method bool isIndonesianIndependenceDay
     * @method bool isIndonesianLaborDay
     * @method bool isIndonesianMothersDay
     * @method bool isKartiniDay
     * @method bool isPancasilaDay
     * @method bool isAssumptionOfMaryFeast
     * @method bool isEpiphany
     * @method bool isImmaculateConceptionFeast
     * @method bool isLiberationDay
     * @method bool isRepublicDay
     * @method bool isSaintStephenDay
     * @method bool isSaintSylvesterDay
     * @method bool isWorkersDay
     * @method bool isKenyanHudumaDay
     * @method bool isKenyanIndependenceDay
     * @method bool isKenyanJamhuriDay
     * @method bool isKenyanLabourDay
     * @method bool isKenyanMadarakaDay
     * @method bool isKenyanMashujaaDay
     * @method bool isKenyanUtamaduniDay
     * @method bool isAllSaintsDay
     * @method bool isChristmasDay
     * @method bool isEasterSunday
     * @method bool isGoodFriday
     * @method bool isNewYearsDay
     * @method bool isNewYearsEve
     * @method bool isOrthodoxChristmasDay
     * @method bool isOrthodoxChristmasEve
     * @method bool isNorthMacedonianDayOfPeoplesUprising
     * @method bool isNorthMacedonianIndependenceDay
     * @method bool isNorthMacedonianRepublicDay
     * @method bool isPolishArmedForcesDay
     * @method bool isPolishConstitutionDay
     * @method bool isPolishEpiphany
     * @method bool isPolishIndependenceDay
     * @method bool isPolishLabourDay
     * @method bool isChristmasEve
     * @method bool isSwedishMidsummerDay
     * @method bool isSwedishNationalDay
     * @method bool isTunisianEvacuationDay
     * @method bool isTunisianIndependenceDay
     * @method bool isTunisianLabourDay
     * @method bool isTunisianMartyrsDay
     * @method bool isTunisianRepublicDay
     * @method bool isTunisianRevolutionAndYouthDay
     * @method bool isTunisianWomensDay
     * @method bool isKupalaNight
     * @method bool isUkraineDefenderDay
     * @method bool isUkrainianConstitutionDay
     * @method bool isUkrainianIndependenceDay
     * @method bool isUkrainianLabourDay
     * @method bool isVictoryDayOverNazism
     * @method bool isAmericanThanksgiving
     * @method bool isColumbusDay
     * @method bool isIndependenceDay
     * @method bool isLaborDay
     * @method bool isMemorialDay
     * @method bool isMlkJrDay
     * @method bool isPresidentsDay
     * @method bool isVeteransDay
     * @method bool isZambianAfricaDay
     * @method bool isZambianAfricanUnityDay
     * @method bool isZambianFarmersDay
     * @method bool isZambianHeroesDay
     * @method bool isZambianIndependenceDay
     * @method bool isZambianLabourDay
     * @method bool isZambianNationalPrayerDay
     * @method bool isZambianUnityDay
     * @method bool isZambianWomensDay
     * @method bool isZambianYouthDay    */
    class Carbon extends \Carbon\Carbon {}
}