name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.3, 8.2, 8.1, 8.0]
        laravel: ["^12.0", "^11.0", "^10.0", "^9.0", "^8.12"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: "^12.0"
            testbench: 10.*
          - laravel: "^11.0"
            testbench: 9.*
          - laravel: "^10.0"
            testbench: 8.*
          - laravel: "^9.0"
            testbench: 7.*
          - laravel: "^8.12"
            testbench: "^6.23"
        exclude:
          - laravel: "^12.0"
            php: 8.1
          - laravel: "^12.0"
            php: 8.0
          - laravel: "^11.0"
            php: 8.1
          - laravel: "^11.0"
            php: 8.0
          - laravel: "^10.0"
            php: 8.0
          - laravel: "^8.12"
            php: 8.3
          - laravel: "^8.12"
            php: 8.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
